language: java
install: true

jdk:
  - oraclejdk8

script:
  - - gradle test
  - ./gradlew build --scan -s
  - ./gradlew sonarqube \
      -Dsonar.projectKey=saifali40_Mocker \
      -Dsonar.organization=saifali40-github \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=$SONAR_TOKEN