os:
  - linux
language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
script:
  - chmod +x gradlew
  - ./gradlew test
  - ./gradlew sonarqube \
    -Dsonar.projectKey=saifali40_Mocker \
    -Dsonar.organization=saifali40-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=$SONAR_TOKEN
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
